In [1]:
# Dependencies
import csv
import pandas as pd
import numpy as np
import requests
import json

# Google API Key
from config import gkey
gkey

'AIzaSyBL8ahyFy8MhoDCjB1wwwb0m3i2cVBBulE'

In [2]:
#read csv file and convert to dataframe
home_prices_df = pd.read_csv('City_Zhvi_SingleFamilyResidence.csv')
home_prices_df.head()

,RegionID,RegionName,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05
0,6181,New York,NY,New York,Queens,1,171900.0,172100.0,172400.0,172500.0,...,550700,555300,558600,561500,564700,570000,576700,583300,589400,593600
1,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,2,166400.0,165900.0,165500.0,164900.0,...,671300,677400,683200,688500,693800,700600,707800,712300,714100,714700
2,17426,Chicago,IL,Chicago,Cook,3,112000.0,113100.0,113900.0,114300.0,...,192300,193400,194900,196600,198500,200800,203100,204800,206300,207100
3,39051,Houston,TX,Houston,Harris,4,89100.0,89000.0,89000.0,89200.0,...,175700,176700,177800,178500,179200,180600,182100,183300,184500,185300
4,13271,Philadelphia,PA,Philadelphia,Philadelphia,5,46100.0,46000.0,45900.0,45800.0,...,130900,132300,133500,134600,135200,136500,138400,139900,140800,141300

In [3]:
home_prices_df.dropna()

,RegionID,RegionName,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05
0,6181,New York,NY,New York,Queens,1,171900.0,172100.0,172400.0,172500.0,...,550700,555300,558600,561500,564700,570000,576700,583300,589400,593600
1,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,2,166400.0,165900.0,165500.0,164900.0,...,671300,677400,683200,688500,693800,700600,707800,712300,714100,714700
2,17426,Chicago,IL,Chicago,Cook,3,112000.0,113100.0,113900.0,114300.0,...,192300,193400,194900,196600,198500,200800,203100,204800,206300,207100
3,39051,Houston,TX,Houston,Harris,4,89100.0,89000.0,89000.0,89200.0,...,175700,176700,177800,178500,179200,180600,182100,183300,184500,185300
4,13271,Philadelphia,PA,Philadelphia,Philadelphia,5,46100.0,46000.0,45900.0,45800.0,...,130900,132300,133500,134600,135200,136500,138400,139900,140800,141300
5,40326,Phoenix,AZ,Phoenix,Maricopa,6,91000.0,91900.0,92700.0,93400.0,...,228200,229700,231500,232800,234200,236500,238700,240100,241400,242400
6,18959,Las Vegas,NV,Las Vegas,Clark,7,132900.0,132600.0,132300.0,132200.0,...,243900,247200,250900,254000,257000,260900,264600,266700,268800,270800
7,6915,San Antonio,TX,San Antonio,Bexar,8,87300.0,87100.0,87000.0,86800.0,...,157900,158900,160000,160800,161600,163100,165000,166500,167200,167400
8,54296,San Diego,CA,San Diego,San Diego,9,178600.0,178500.0,178300.0,178000.0,...,667300,671200,674900,678400,682400,689300,696900,701500,702000,700800
9,38128,Dallas,TX,Dallas-Fort Worth,Dallas,10,80800.0,81000.0,81300.0,81500.0,...,179600,182500,184400,185500,186600,188900,191900,194500,196800,199000
10,33839,San Jose,CA,San Jose,Santa Clara,11,238200.0,238900.0,239700.0,240700.0,...,984400,1003900,1024400,1046500,1066000,1091500,1123000,1146900,1165700,1182700
11,25290,Jacksonville,FL,Jacksonville,Duval,12,76600.0,76200.0,75900.0,75800.0,...,158300,160300,161800,163100,164800,166700,168200,169100,170000,170500
12,20330,San Francisco,CA,San Francisco,San Francisco,13,264500.0,264500.0,264500.0,264600.0,...,1306600,1320500,1337900,1350000,1356400,1368200,1383300,1394900,1408400,1420600
13,32149,Indianapolis,IN,Indianapolis,Marion,14,112200.0,109800.0,107300.0,104800.0,...,120100,120600,121500,122600,123800,125200,126300,127100,128500,129700
14,10221,Austin,TX,Austin,Travis,15,169800.0,169900.0,170800.0,172100.0,...,337700,338000,339700,342700,346000,349700,354100,357300,358700,359000
15,18172,Fort Worth,TX,Dallas-Fort Worth,Tarrant,16,92800.0,93100.0,93400.0,93800.0,...,169600,170900,172400,174100,175800,177800,180200,181500,182100,182600
16,10920,Columbus,OH,Columbus,Franklin,17,88900.0,89000.0,89100.0,89300.0,...,142300,143500,144900,146900,148600,149800,150300,150800,152100,153400
17,32811,Memphis,TN,Memphis,Shelby,18,58700.0,58800.0,59000.0,59200.0,...,74200,75000,75400,75900,76700,77500,77800,77900,78300,78600
18,24043,Charlotte,NC,Charlotte,Mecklenburg,19,115500.0,116000.0,116500.0,117000.0,...,198700,201000,203100,205300,207500,209900,212500,214700,216400,217400
19,17933,El Paso,TX,El Paso,El Paso,20,78200.0,78000.0,77700.0,77600.0,...,120900,121400,121800,121800,121800,121900,122200,122600,123100,123400
20,44269,Boston,MA,Boston,Suffolk,21,124000.0,124800.0,125900.0,127200.0,...,537700,539100,542100,546200,549100,554200,562200,568800,573400,576200
21,16037,Seattle,WA,Seattle,King,22,169100.0,169300.0,169500.0,169900.0,...,737200,743300,751000,760000,769700,782300,792600,795800,797200,799000
22,11093,Denver,CO,Denver,Denver,23,119200.0,119400.0,119700.0,120000.0,...,421800,423200,425000,427100,429900,435400,442100,446700,448900,449500
23,41568,Washington,DC,Washington,District of Columbia,24,121300.0,120800.0,120300.0,120000.0,...,656400,659100,660600,661400,662100,664800,671200,677400,680800,682100
24,6118,Nashville,TN,Nashville,Davidson,25,97700.0,97900.0,98000.0,98200.0,...,241200,243300,245300,246700,248200,251300,255100,258000,259800,260900
25,5976,Milwaukee,WI,Milwaukee,Milwaukee,26,68100.0,68100.0,68000.0,67900.0,...,105700,106800,108200,109500,110500,111800,113000,113300,113500,113600
26,7481,Tucson,AZ,Tucson,Pima,27,95600.0,95600.0,95700.0,95900.0,...,175400,176800,178400,180200,181500,182800,184300,185600,186600,187200
27,13373,Portland,OR,Portland,Multnomah,28,119000.0,119900.0,120900.0,121800.0,...,425200,425100,424900,425500,427000,430400,434700,436500,435800,434800
28,33225,Oklahoma City,OK,Oklahoma City,Oklahoma,29,53900.0,54900.0,55700.0,56300.0,...,125800,125900,126300,126700,127000,127300,127500,127500,127500,127400
29,40152,Omaha,NE,Omaha,Douglas,30,95800.0,96600.0,97000.0,97100.0,...,157800,158500,159200,160100,161000,162000,163300,164300,165200,166300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12820,49693,Piney Point,MD,California-Lexington Park,Saint Marys,12821,123900.0,124000.0,124200.0,124300.0,...,310400,313200,314200,313500,312100,311600,312000,312200,311500,310200
12822,50457,Drumright,OK,Tulsa,Creek,12823,20200.0,20300.0,20300.0,20400.0,...,37800,38100,38200,38300,38600,39200,40400,41800,43400,44800
12823,50539,Middleton,ID,Boise City,Canyon,12824,104600.0,104800.0,105200.0,105700.0,...,201700,206300,209200,210600,212300,215900,219700,222600,225500,228000
12825,50692,Almo,KY,Murray,Calloway,12826,55700.0,56400.0,57000.0,57700.0,...,120800,119600,120200,120400,120100,119800,120400,121800,123300,123600
12826,50963,Bennett,CO,Denver,Adams,12827,89100.0,89800.0,90500.0,91200.0,...,250400,252800,255100,257900,260900,264600,268100,270200,271600,272700
12827,51632,Dafter,MI,Sault Ste. Marie,Chippewa,12828,48500.0,48700.0,49000.0,49200.0,...,98400,99500,99200,98700,99000,99000,97800,96800,96400,96100
12828,51793,East Hampstead,NH,Boston,Rockingham,12829,135100.0,135500.0,136000.0,136400.0,...,328600,330700,333300,336300,338200,339400,340600,341700,343500,345800
12829,51901,Emily,MN,Brainerd,Crow Wing,12830,67800.0,67500.0,67200.0,66900.0,...,183000,183900,183400,182800,182600,184200,188300,191400,193300,194900
12830,52166,Garden City,MO,Kansas City,Cass,12831,70800.0,70900.0,71000.0,71100.0,...,112200,113200,114700,117100,118900,120200,121500,121400,121100,122100
12831,52374,Hager City,WI,Minneapolis-St Paul,Pierce,12832,111000.0,110400.0,109700.0,109000.0,...,192400,193500,194500,195500,196600,197200,197200,197100,197300,197700
12832,53456,Mountainburg,AR,Fort Smith,Crawford,12833,27200.0,27300.0,27400.0,27600.0,...,92100,92000,91700,91500,91400,92300,93900,94700,95100,96500
12833,53678,Ocoee,TN,Cleveland,Polk,12834,39200.0,39800.0,40500.0,41200.0,...,124800,123000,122100,122100,122500,123600,126500,129600,131000,131300
12834,54802,Upper Brookville,NY,New York,Nassau,12835,767200.0,769500.0,771700.0,773800.0,...,1958900,1969200,1989400,2001000,2003600,1997000,1984000,1978200,1973800,1963500
12836,55210,Williamston,MI,Lansing,Ingham,12837,76900.0,76800.0,76800.0,76800.0,...,188100,189100,190700,192700,193500,193900,195000,196800,198500,199200
12837,55357,Decatur,AR,Fayetteville,Benton,12838,52500.0,52800.0,53100.0,53300.0,...,111300,112000,112800,110200,105300,106000,111900,118200,121200,123000
12838,55706,Edgewood,IN,Indianapolis,Madison,12839,67300.0,67500.0,67700.0,68000.0,...,109800,110500,110600,110700,111300,112200,112300,112200,114100,116600
12839,56183,Palmyra,TN,Clarksville,Montgomery,12840,56100.0,56400.0,56700.0,57000.0,...,161700,163100,164500,166500,168100,169200,169900,171300,173800,175200
12841,57212,Forest Falls,CA,Riverside,San Bernardino,12842,90000.0,89900.0,89800.0,89700.0,...,213800,217400,221500,226500,233900,239400,239300,237700,239300,242200
12842,114834,East Pasadena,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,12843,233500.0,234700.0,236000.0,237100.0,...,907900,914700,921000,928800,939900,954600,970500,981100,993400,1006900
12843,115391,Green Valley,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,12844,109100.0,108800.0,108400.0,108000.0,...,253600,257000,260300,265900,271100,272200,269900,269800,272100,274200
12844,182023,Henrico,VA,Richmond,Henrico,12845,111400.0,111600.0,111800.0,112000.0,...,228400,229800,231100,232500,233800,235800,238700,241500,243500,244600
12845,188693,Diamond Beach,NJ,Ocean City,Cape May,12846,164000.0,163500.0,162900.0,162300.0,...,453100,451000,451000,452300,451000,452900,459800,468500,476300,481000
12846,214624,Plymptonville,PA,DuBois,Clearfield,12847,30100.0,30100.0,30000.0,30000.0,...,49300,50700,51000,50300,49700,49700,50400,51300,52900,54300
12847,237360,Saint Paul,TX,Dallas-Fort Worth,Collin,12848,160600.0,160800.0,161000.0,161300.0,...,322900,324200,324400,325300,326200,328500,333300,338300,340900,342800
12848,398292,Wrightstown,WI,Green Bay,Brown,12849,111100.0,110800.0,110400.0,110000.0,...,185700,185300,186900,189900,191400,190900,190900,191900,192400,192300
12849,398343,Urbana,NY,Corning,Steuben,12850,67500.0,67400.0,67200.0,67100.0,...,130100,130700,131400,132800,134900,137700,139800,141100,141400,141900
12850,398496,New Denmark,WI,Green Bay,Brown,12851,112200.0,112900.0,113800.0,114700.0,...,223100,227000,227800,226000,220800,216400,214600,214100,212800,211600
12851,398608,Rochester,WI,Racine,Racine,12852,126000.0,126500.0,126800.0,126800.0,...,252600,254300,254300,254000,255800,259000,261500,263100,266100,269200
12852,737788,Lebanon Borough,NJ,New York,Hunterdon,12853,159800.0,159800.0,159700.0,159600.0,...,266000,264500,265700,268000,272100,277400,280900,280400,277600,274400
12853,760887,Berlin Borough,NJ,Philadelphia,Camden,12854,119700.0,119600.0,119500.0,119300.0,...,210300,213800,216300,217700,217900,217900,218500,220100,221600,222500

In [4]:
#filter original dataframe to contain records for only cities in Los Angeles county
home_prices_df = home_prices_df.loc[home_prices_df.CountyName == "Los Angeles"]
home_prices_df.head()

,RegionID,RegionName,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05
1,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,2,166400.0,165900.0,165500.0,164900.0,...,671300,677400,683200,688500,693800,700600,707800,712300,714100,714700
34,46298,Long Beach,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,35,163600.0,163300.0,162900.0,162600.0,...,604500,610500,615300,618900,621700,625900,630400,633100,633700,633200
125,45457,Glendale,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,126,243700.0,243400.0,243100.0,242600.0,...,874900,881800,888700,894700,900400,908100,916600,922500,926000,927000
140,5534,Lancaster,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,141,102300.0,101600.0,100800.0,100000.0,...,253900,257600,261000,264100,266900,270400,273900,276100,277800,279200
162,40227,Palmdale,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,163,107100.0,106900.0,106600.0,106300.0,...,284000,287400,290300,293500,297000,300700,304000,306600,308500,309700

In [59]:
#delete data columns not needed for data analysis 
del home_prices_df['RegionID']
del home_prices_df['Metro']
del home_prices_df['SizeRank']

home_prices_df.head()

,RegionName,State,CountyName,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,1996-10,...,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05
1,Los Angeles,CA,Los Angeles,166400.0,165900.0,165500.0,164900.0,164500.0,164100.0,163800.0,...,671300,677400,683200,688500,693800,700600,707800,712300,714100,714700
34,Long Beach,CA,Los Angeles,163600.0,163300.0,162900.0,162600.0,162300.0,162000.0,162000.0,...,604500,610500,615300,618900,621700,625900,630400,633100,633700,633200
125,Glendale,CA,Los Angeles,243700.0,243400.0,243100.0,242600.0,242300.0,242100.0,242100.0,...,874900,881800,888700,894700,900400,908100,916600,922500,926000,927000
140,Lancaster,CA,Los Angeles,102300.0,101600.0,100800.0,100000.0,99200.0,98400.0,97700.0,...,253900,257600,261000,264100,266900,270400,273900,276100,277800,279200
162,Palmdale,CA,Los Angeles,107100.0,106900.0,106600.0,106300.0,106000.0,105700.0,105600.0,...,284000,287400,290300,293500,297000,300700,304000,306600,308500,309700

In [60]:
unique_cities = len(home_prices_df['RegionName'].unique())
print(f'Dataset contains historical home price data for {unique_cities} cities in Los Angeles County.')

Dataset contains historical home price data for 113 cities in Los Angeles County.

In [61]:
#read csv file and convert to dataframe
zipcode_cities_df = pd.read_csv('zip_codes_states_LA_COUNTY.csv')
zipcode_cities_df.head()

   zip_code   latitude   longitude   RegionName State   CountyName
0     90001  33.973951 -118.248405  Los Angeles    CA  Los Angeles
1     90002  33.950514 -118.245855  Los Angeles    CA  Los Angeles
2     90003  33.949164 -118.273156  Los Angeles    CA  Los Angeles
3     90004  33.786594 -118.298662  Los Angeles    CA  Los Angeles
4     90005  33.786594 -118.298662  Los Angeles    CA  Los Angeles

In [62]:
len(zipcode_cities_df)

531

In [42]:
#unique cities in Los Angeles count
zipcode_cities_df['RegionName'].unique()

array(['Los Angeles', 'West Hollywood', 'Bell', 'Bell Gardens',
       'Beverly Hills', 'Compton', 'Culver City', 'Downey', 'El Segundo',
       'Gardena', 'Hawthorne', 'Hermosa Beach', 'Huntington Park',
       'Lawndale', 'Lynwood', 'Malibu', 'Manhattan Beach', 'Maywood',
       'Pacific Palisades', 'Palos Verdes Peninsula',
       'Rancho Palos Verdes', 'Redondo Beach', 'South Gate', 'Topanga',
       'Venice', 'Marina Del Rey', 'Playa Del Rey', 'Inglewood',
       'Santa Monica', 'Torrance', 'Whittier', 'La Mirada', 'Montebello',
       'Norwalk', 'Pico Rivera', 'Santa Fe Springs', 'Artesia',
       'Cerritos', 'Avalon', 'Bellflower', 'Harbor City', 'Lakewood',
       'Hawaiian Gardens', 'Lomita', 'Paramount', 'San Pedro',
       'Wilmington', 'Carson', 'Long Beach', 'Altadena', 'Arcadia',
       'Duarte', 'La Canada Flintridge', 'Monrovia', 'Montrose',
       'Mount Wilson', 'Sierra Madre', 'South Pasadena', 'Sunland',
       'Tujunga', 'Verdugo City', 'Pasadena', 'San Marino', 'Glendale',
       'La Crescenta', 'Agoura Hills', 'Calabasas', 'Canoga Park',
       'Winnetka', 'West Hills', 'Castaic', 'Chatsworth', 'Encino',
       'Newhall', 'Northridge', 'Pacoima', 'Reseda', 'San Fernando',
       'Sylmar', 'North Hills', 'Granada Hills', 'Mission Hills',
       'Santa Clarita', 'Canyon Country', 'Sun Valley', 'Valencia',
       'Tarzana', 'Westlake Village', 'Woodland Hills', 'Stevenson Ranch',
       'Van Nuys', 'Panorama City', 'Sherman Oaks', 'Burbank',
       'North Hollywood', 'Studio City', 'Valley Village',
       'Universal City', 'Toluca Lake', 'Azusa', 'Baldwin Park',
       'Claremont', 'City Of Industry', 'Covina', 'El Monte',
       'South El Monte', 'Glendora', 'La Puente', 'Hacienda Heights',
       'Rowland Heights', 'La Verne', 'Monterey Park', 'Mt Baldy',
       'Diamond Bar', 'Pomona', 'Rosemead', 'San Dimas', 'San Gabriel',
       'Temple City', 'Walnut', 'West Covina', 'Alhambra', 'Acton',
       'Lake Hughes', 'Lancaster', 'Littlerock', 'Llano', 'Palmdale',
       'Pearblossom', 'Valyermo'], dtype=object)

In [63]:
#nicola's dataset zipcode,lat long,cityname
un_zipcode_city=zipcode_cities_df['RegionName'].unique()
len(un_zipcode_city)

130

In [64]:
home_price_list = list(home_prices_df['RegionName'])

In [65]:
#zillow
len(home_price_list)

113

In [30]:
city_data=[]
#zipcode_cities_df
home_price_list = list(home_prices_df['RegionName'])
zipcode_cities_list = list(zipcode_cities_df['RegionName'].unique())
for home_price_city in home_price_list:
    if home_price_city in zipcode_cities_list:
        city_data.append(home_price_city)

print('Cities with home price data in Zillow dataset:\n')
print(city_data)
print('')
print(f'{len(city_data)} cities in Los Angeles County with home price data.')

Cities with home price data in Zillow dataset:

['Los Angeles', 'Long Beach', 'Glendale', 'Lancaster', 'Palmdale', 'Santa Clarita', 'Pomona', 'Pasadena', 'Torrance', 'Inglewood', 'Compton', 'Downey', 'Norwalk', 'El Monte', 'Burbank', 'West Covina', 'South Gate', 'Santa Monica', 'Hawthorne', 'Alhambra', 'Lakewood', 'Whittier', 'Carson', 'Bellflower', 'Covina', 'Baldwin Park', 'Huntington Park', 'Redondo Beach', 'Lynwood', 'Pico Rivera', 'Rosemead', 'Arcadia', 'San Gabriel', 'Gardena', 'Monterey Park', 'Azusa', 'Montebello', 'Glendora', 'Hacienda Heights', 'Paramount', 'La Mirada', 'Diamond Bar', 'Cerritos', 'Bell Gardens', 'Monrovia', 'Rowland Heights', 'La Puente', 'Altadena', 'Culver City', 'Beverly Hills', 'Bell', 'West Hollywood', 'Manhattan Beach', 'Rancho Palos Verdes', 'Lawndale', 'San Dimas', 'Temple City', 'Walnut', 'Claremont', 'Maywood', 'South Pasadena', 'San Fernando', 'La Verne', 'Agoura Hills', 'South El Monte', 'Lomita', 'La Canada Flintridge', 'Duarte', 'Hermosa Beach', 'El Segundo', 'Artesia', 'Santa Fe Springs', 'Calabasas', 'Hawaiian Gardens', 'Castaic', 'Malibu', 'Sierra Madre', 'San Marino', 'Littlerock', 'Topanga', 'Acton', 'Avalon', 'Pearblossom', 'Palos Verdes Peninsula', 'Lake Hughes']

85 cities in Los Angeles County with home price data.

In [66]:
csvfile = "city_data.csv"
#Assuming res is a flat list
with open(csvfile, "w") as output:
    writer = csv.writer(output, lineterminator='\n')
    for val in city_data:
        writer.writerow([val])